spring:
  data:
    mongodb:
      username: nikita
      password: nikita
      hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090

